services:
  - type: web
    name: i140tracker-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://i140tracker-backend.onrender.com
